# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Curious Thoughts
email: swarajpalsaaj@yahoo.co.in
description: > # this means to ignore newlines until "baseurl:"
  Tech Thoughts by Swaraj
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: swarajsaaj
github_username:  swarajsaaj

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge